name: Install packages

on:
  pull_request:
    branches: [main]
    types: [labeled, synchronize]
    paths:
      - package.json

jobs:
  resolve-pnpm-lock-conflicts:
    name: Resolve pnpm-lock Conflicts
    if: |
      (github.event.action == 'labeled' && contains(fromJSON('["QUEUED FOR MERGE #1, JUMP THE QUEUE"]'), github.event.label.name))
      ||
      (github.event.action == 'synchronize' && contains(fromJSON('["QUEUED FOR MERGE #1, JUMP THE QUEUE"]'), github.event.pull_request.labels.*.name))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node and pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Authenticate with GitHub CLI
        run: |
          git config --local user.name 'github-actions'
          git config --local user.email 'github-actions@users.noreply.github.com'

      - name: Install Packages
        run: |
          pnpm i --frozen-lockfile=false
          git -f add pnpm-lock.yaml
          git status --short
          if [[ `git status --porcelain` ]]; then
            git commit -m "update pnpm-lock.yaml"
          fi
          git push
