name: Post-Merge Actions
on:
  workflow_run:
    workflows: ["Manage Merge Queue"]
    types:
      - completed

jobs:
  post-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Run test
        run: echo "test"
