name: Handle pnpm-lock Conflicts

on:
  workflow_dispatch:
    inputs:
      prnumber:
        description: Pull Request number
        type: text
        required: true

  push:
    branches: [main]

jobs:
  conflicts:
    name: Identify conflicts
    runs-on: ubuntu-latest
    outputs:
      has_conflicts: ${{ steps.has-conflicts.outputs.has_conflicts }}
      pr_number: ${{ steps.pr-number.outputs.pr_number }}
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    steps:
      - name: Wait for 1 minute
        if: github.event_name == 'push'
        run: sleep 60

      - name: Authenticate with GitHub CLI
        run: |
          gh auth status
          git config --local user.name 'github-actions'
          git config --local user.email 'github-actions@users.noreply.github.com'

      - name: Grab PR number
        id: pr-number
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            pr_number="${{ github.event.inputs.prnumber }}"
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            pr_number=$(gh pr list --state open --label 'READY FOR MERGE' --label 'QUEUED FOR MERGE #1' --json number --jq '.[] | .number')
          fi
  
          if [[ "$pr_number" ]]; then
            echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
          else
            echo "Didn't find PR to resolve conflicts" 
            exit 0
          fi

      - name: Check if PR has conflicts
        id: has-conflicts
        run: |
          mergeable=$(gh pr view ${{ steps.pr-number.outputs.pr_number }} --json mergeable --jq '.mergeable')
          echo $mergeable
          
          if [[ "$mergeable" == "UNKNOWN" ]]; then
            echo "wait for 30 seconds..."
            sleep 30
            mergeable=$(gh pr view ${{ steps.pr-number.outputs.pr_number }} --json mergeable --jq '.mergeable')
            echo $mergeable
          fi
          
          if [[ "$mergeable" == "CONFLICTING" ]]; then
            echo "has_conflicts=true" >> $GITHUB_OUTPUT
          else
            echo "has_conflicts=false" >> $GITHUB_OUTPUT
          fi

  resolve-conflicts:
    name: Resolve conflicts
    needs: conflicts
    if: ${{ needs.conflicts.outputs.has_conflicts == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node and pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install packages
        run: pnpm i

      - name: Attempt to resolve conflicts
        run: |
          gh pr checkout ${{ needs.conflicts.outputs.pr_number }}
          git fetch origin main
          git merge origin/main || true
          git checkout --ours package.json
          node script/resolve-conflicts/merge-package-json.js
          
          git status --short
          if [[ `git status --porcelain` ]]; then
            git add package.json pnpm-lock.yaml
            git commit -m "resolve conflicts in package.json and pnpm-lock.yaml"
          fi
          git push
